name: sudoku_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.18
  - flask=2.2.3
  - werkzeug=2.2.3
  - sphinx=4.2.0
  - sphinx_rtd_theme=1.0.0
  - sphinx-build=5.0.2
  - pytest=6.2.5
